name: Deploy via SSH
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Run unit tests
        working-directory: backend
        run: npm run test:unit

      - name: Run integration tests
        working-directory: backend
        run: npm run test:integration

  deploy:
    needs: test
    if github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: citrus-kit.com
          username: 'root'
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/CitrusKit/
            git pull
            cd frontend
            npm ci
            npm run build
            systemctl reload nginx
            cd ../backend
            npm ci
            pm2 restart server --update-env
